image: gitpod/workspace-full

ports:
  - port: 4001
    onOpen: open-preview

tasks:
  - init: yarn install && bundle install
    command: env PORT=4001 yarn run dev

github:
  # Prebuild the docker image for gitpod - https://www.gitpod.io/docs/prebuilds/
  prebuilds:
    # enable for the master/default branch
    master: true
