// Generates src/sass/2017/icons.generated.scss: the mask URIs behind
// `@include icon(…)`, see src/sass/2017/utils/_icon.scss.
//
// Brand marks that can live in markup use src/components/Icon.astro instead.
//
// Run by `pnpm dev` and `pnpm build`; checked by `pnpm icons:check`.
import { readFileSync, renameSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { icons } from '@iconify-json/ion'
import { getIconData, iconToHTML, iconToSVG, svgToURL } from '@iconify/utils'

const USED = [
  'md-arrow-back',
  'md-arrow-forward',
  'md-search',
  'md-chatboxes',
  'md-information-circle',
  'ios-home-outline',
  'ios-flash',
  'ios-arrow-back'
]

const output = fileURLToPath(
  new URL('../src/sass/2017/icons.generated.scss', import.meta.url)
)

function render() {
  const entries = USED.map((name) => {
    // getIconData() merges the set's 512×512 default; the per-icon records
    // have no width/height of their own.
    const icon = getIconData(icons, name)
    if (!icon) throw new Error(`Unknown icon in the "ion" set: ${name}`)

    const { body, viewBox } = iconToSVG(icon)
    const svg = iconToHTML(
      // A mask only reads the alpha channel, so flatten the fill colour.
      body.replaceAll('currentColor', 'black'),
      {
        viewBox: viewBox.join(' '),
        width: `${viewBox[2]}`,
        height: `${viewBox[3]}`
      }
    )

    return `  '${name}': ${svgToURL(svg)},`
  })

  return [
    '// GENERATED by scripts/build-icons.mjs — do not edit.',
    '// Regenerate with: pnpm icons',
    '',
    '$icon-data: (',
    ...entries,
    ');',
    ''
  ].join('\n')
}

function current() {
  try {
    return readFileSync(output, 'utf8')
  } catch {
    return ''
  }
}

const next = render()

if (next === current()) {
  console.log('icons.generated.scss is up to date')
} else if (process.argv.includes('--check')) {
  console.error('icons.generated.scss is stale — run: pnpm icons')
  process.exit(1)
} else {
  // Written to a temp file first: `pnpm ci` runs `icons:check` and `build`
  // concurrently, and the check must never read a half-written file.
  writeFileSync(`${output}.tmp`, next)
  renameSync(`${output}.tmp`, output)
  console.log('wrote src/sass/2017/icons.generated.scss')
}
